version: "3.8"
services:
  traefik:
    image: traefik:latest
    container_name: TRAEFIK
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./etc/traefik/config/:/etc/traefik/config/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    restart: always
networks:
  default:
    name: traefik-proxy
