version: "3.8"
services:
  traefik:
    image: traefik:latest
    container_name: TRAEFIK
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - traefik-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    restart: always
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.myhttpchallenge.acme.email=david.vanmak@pop-france.eu"
      - "--certificatesResolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.myhttpchallenge.acme.httpChallenge.entryPoint=web"
      - "--middlewares.SecHeader.headers.forceSTSHeader=true"
      - "--middlewares.SecHeader.headers.stsIncludeSubdomains=true"
      - "--middlewares.SecHeader.headers.stsSeconds=31536000"
      - "--middlewares.SecHeader.headers.sslRedirect=true"
      - "--middlewares.SecHeader.headers.contentSecurityPolicy=script-src 'self'; img-src 'self'"
      - "--middlewares.SecHeader.headers.referrerPolicy=same-origin"
      - "--middlewares.SecHeader.headers.featurePolicy=vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"
      - "--middlewares.SecHeader.headers.frameDeny=true"
      - "--middlewares.SecHeader.headers.contentTypeNosniff=true"
      - "--middlewares.SecHeader.headers.browserXssFilter=true"
      - "--tls.options=default.minVersion=VersionTLS12"
      - "--tls.options=default.sniStrict=true"
      - "--entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0,::/0"  # Enable Proxy Protocol
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=0.0.0.0/0,::/0"  # Enable Proxy Protocol
      - "--serversTransport.forwardingHeaders.insecure=true"  # Allow insecure forwarding headers
      - "--serversTransport.forwardingHeaders.trustedIPs=0.0.0.0/0,::/0"  # Allow forwarding headers from any IP address

networks:
  default:
    name: traefik-proxy

volumes:
  traefik-letsencrypt:
